### ISSUE TITLE
Two hole chain wire anchor is mistakenly named 3 hole

### ISSUE THREAD

**Issue by rlaferla** [VoronDesign/Voron-Trident#75]
https://github.com/VoronDesign/Voron-Trident/blob/VTr1/STLs/Gantry/chain_wire_anchor_a_3hole.stl

chain_wire_anchor_a_3hole.stl => chain_wire_anchor_a_2hole.stl

**Comment by rh101** [comment]
Are you sure this is a mistake? From my understanding, this STL is used with the generic 3-hole cable chain, which is why it has "3hole" in the name, since those cable chains don't come with an anchor point/strain relief.  The name of the STL doesn't actually have anything to do with the number of screw holes in the model.
