### ISSUE TITLE
Mains inlet wiring on p236 is backwards

### ISSUE THREAD

**Issue by wrwindsor** [VoronDesign/Voron-Trident#82]
If you're looking into the plug end of the mains inlet wiring, ground tang up, "neutral" is on the left and "line" is on the right.

see: https://www.electronics2000.co.uk/pin-out/iec.php (IEC 63020 pin assignment for C13/C14)

Therefore, if you're looking at the back of the filtered inlet (for purposes of running wiring), ground tang up, it is reversed -- the "line" tab is on the right and the "neutral" tab is on the left.

The wire coloring in the drawing on p236 is backwards of this.

**Comment by rh101** [comment]
I was about to post about this issue as well. 

FYI, the Voron 2 manual shows it with the correct wiring.

**Comment by rh101** [comment]
It's definitely incorrect in the Trident manual.  The Voron 2 manual shows it with the correct wiring.

**Comment by BerzerkaDurk** [comment]
This has happened before. Issue #45. It was fixed then, but it looks like at some point between then and now, they flipped the orientation of the power inlet 180 degrees in the manual, but they didn't swap the wire colors.

Previous manual, correct wiring:
![image](https://user-images.githubusercontent.com/81716812/201169857-ffcf356f-6775-40a5-a2f2-79fd83726e0a.png)

Current manual, incorrect wiring:
![image](https://user-images.githubusercontent.com/81716812/201169952-e94e6e50-34f7-42f9-9d3c-e7bd950cbaf4.png)

**Comment by BerzerkaDurk** [comment]
I'm going to start an engineering ticket on the Discord. This needs to be corrected immediately. It's a fire hazard. If someone is using the single fused inlet, wired backward, and there is a short to ground, it will short the hot wire right to ground with no fuse protection.

**Comment by BerzerkaDurk** [comment]
It should be noted that the wiring on page 237 will have to be corrected, as well.

**Comment by SirOink** [comment]
still hasn't been fixed, may 11th 2023. I see this as a major issue due to the amount of low quality kits out and about combined with self-sourcing from non-eu/us countries (the bom filtered power inlet is hard to find in some places, let alone dual fused filtered inlets)

luckily I'm pedantic about safety, I read my power inlet's data sheet & googled IEC ordering, else I'd have fell for it too as I'm 
a. dyslexic
&
b. don't like watching 4 hour long (or even 10 minute long) video tutorials. I prefer written ones, so the manual has been my gospel. I'm surely not alone, hopefully the others have backup fuses bc the devs don't seem to care about updating the trident manual/trident seems to be the red headed stepchild 🤷‍♂️

**Comment by nemgrea** [comment]
fixed
